# Generated by Django 4.0.4 on 2022-05-16 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='mdl_events',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False, verbose_name='id')),
                ('eventname', models.CharField(default='', max_length=255, verbose_name='eventname')),
                ('component', models.CharField(default='', max_length=255, verbose_name='component')),
                ('action', models.CharField(default='', max_length=255, verbose_name='action')),
                ('target', models.CharField(default='', max_length=255, verbose_name='target')),
                ('objecttable', models.CharField(default='', max_length=255, verbose_name='objecttable')),
                ('objectid', models.BigIntegerField(default=0, verbose_name='objectid')),
                ('crud', models.CharField(default='', max_length=255, verbose_name='crud')),
                ('edulevel', models.SmallIntegerField(verbose_name='edulevel')),
                ('contextid', models.BigIntegerField(verbose_name='contextid')),
                ('contextlevel', models.BigIntegerField(verbose_name='contextlevel')),
                ('contextinstanceid', models.BigIntegerField(verbose_name='contextinstanceid')),
                ('userid', models.BigIntegerField(verbose_name='userid')),
                ('courseid', models.BigIntegerField(default=0, verbose_name='courseid')),
                ('relateduserid', models.BigIntegerField(default=0, verbose_name='relateduserid')),
                ('anonymous', models.SmallIntegerField(default=0, verbose_name='anonymous')),
                ('timecreated', models.BigIntegerField(verbose_name='timecreated')),
                ('origin', models.CharField(default='', max_length=255, verbose_name='origin')),
                ('ip', models.CharField(default='', max_length=255, verbose_name='ip')),
                ('realuserid', models.BigIntegerField(default=0, verbose_name='realuserid')),
            ],
        ),
    ]
