# Generated by Django 4.0.4 on 2022-06-02 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle_events', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mdl_events',
            name='other',
            field=models.JSONField(verbose_name='other'),
        ),
    ]
