# Generated by Django 4.0.4 on 2022-05-16 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('moodle_events', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='mdl_events',
            name='other',
            field=models.TextField(default='', verbose_name='other'),
        ),
    ]
