# Generated by Django 4.0.4 on 2022-06-03 22:02

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='course_on_categories',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('fullname', models.CharField(default='', max_length=250)),
                ('displayname', models.CharField(default='', max_length=250)),
                ('shortname', models.CharField(default='', max_length=250)),
                ('categoryid', models.CharField(default='', max_length=250)),
                ('categoryname', models.CharField(default='', max_length=250)),
            ],
        ),
        migrations.CreateModel(
            name='departments',
            fields=[
                ('id', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=200)),
                ('description', models.CharField(max_length=200)),
                ('descriptionformat', models.IntegerField()),
                ('parent', models.IntegerField()),
                ('sortorder', models.IntegerField()),
                ('coursecount', models.IntegerField()),
                ('depth', models.IntegerField()),
                ('path', models.CharField(max_length=200)),
            ],
        ),
    ]
