# Generated by Django 4.0.4 on 2022-06-04 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_on_categories',
            name='displayname',
            field=models.TextField(default=''),
        ),
        migrations.AlterField(
            model_name='course_on_categories',
            name='fullname',
            field=models.TextField(default=''),
        ),
    ]
