# Generated by Django 4.0.4 on 2022-06-05 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('adminpanel', '0002_alter_course_on_categories_displayname_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='course_on_categories',
            name='categoryid',
            field=models.IntegerField(),
        ),
    ]
